databases:
  - name: sase-student-portal-db
    databaseName: sase_student_portal
    plan: free

services:
  - type: web
    name: sase-student-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OFFICER_INVITE_CODE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sase-student-portal-db
          property: connectionString
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_CLAIMS_SUBJECT
        value: mailto:ryankreger364@gmail.com
